version: "3.9"
services:
  web:
    build:
      dockerfile: Dockerfile
    platform: linux/x86_64
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3001:3000"
    depends_on:
      - db
    links:
      - db
    volumes:
      - ".:/app"
    environment:
      DB_USER: root
      DB_NAME: mpooldev
      DB_PASSWORD: password
      DB_HOST: db
  db:
    image: "mysql"
    restart: always
    volumes:
      - app_db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: mpooldev
      MYSQL_ROOT_PASSWORD: password
volumes:
  app_db: